@startuml Job
skinparam defaultFontName D2Coding

scale 2
title Job

interface Job {
  +void excute(JobExecution)
}
abstract class AbstractJob {
  name : job 이름
  restartable : 재시작 여부
  JobRepository : 메타데이터 저장소
  JobExecutionListener : Job 이벤트 리스너
  JobParametersIncrementer : JobParamter 증가기
  JobParametersValidator : JobParameter 검증기
  SimpleStepHandler : Step 실행 핸들러
}

class FlowJob {
  flow
}

class SimpleJob {
  step
}

Job <|-- AbstractJob
AbstractJob <|-- FlowJob
AbstractJob <|-- SimpleJob


@enduml
