@startwbs Spring Boot Actuator Endpoints
* Endpoint
** auditevents
** beans
** caches
** conditions
** configprops
** env
** flyway
** health
*** cassandra
*** couchbase
*** db
*** diskspace
*** elasticsearch
*** hazelcast
*** influxdb
*** jms
*** ldap
*** mail
*** mongo
*** neo4j
*** ping
*** rabbit
*** redis
*** livenessstate
*** readinessstate
** httpexchanges
** info
** integrationgraph
** loggers
** liquibase
** metrics
** mappings
** quartz
** scheduledtasks
** sessions
** shutdown
** startup
** threaddump
@endwbs